DROP DATABASE IF EXISTS CAR_RENTAL;
CREATE DATABASE CAR_RENTAL;
USE CAR_RENTAL;

DROP TABLE IF EXISTS AGENCY;
DROP TABLE IF EXISTS AGENT;
DROP TABLE IF EXISTS CARS;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS REVIEWS;

DROP TABLE IF EXISTS AGENCY;
CREATE TABLE AGENCY
(
	city VARCHAR(50),
    zip INT,
    rentDate DATE,
    dueDate DATE,
    aID INT,
    rID INT
);

CREATE TABLE AGENT
(
	aID INT,
    cID INT,
    city VARCHAR(50)
);

CREATE TABLE CARS
(
	model INT,
    year INT,
    brand VARCHAR(50),
    color VARCHAR(10),
    type VARCHAR(10),
    carID INT
);

CREATE TABLE CUSTOMER
(
	cID INT,
    aID INT,
    insurance VARCHAR(50),
    carID INT
);

CREATE TABLE REVIEWS
(
	rID INT,
    cID INT,
    stars INT
);