DROP DATABASE IF EXISTS CAR_RENTAL;
CREATE DATABASE CAR_RENTAL;
USE CAR_RENTAL;

DROP TABLE IF EXISTS AGENCY;
DROP TABLE IF EXISTS BOOKING;
DROP TABLE IF EXISTS CARS;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS REVIEWS;

CREATE TABLE AGENCY
(
	agencyID INT PRIMARY KEY,
    city VARCHAR(50),
    reviewID INT REFERENCES REVIEWS(reviewID),
    bookingID INT REFERENCES BOOKING(bookingID)
);

CREATE TABLE BOOKING
(
	bookingID INT PRIMARY KEY,
    carID INT REFERENCES CARS(carID),
    rentDate date,
    dueDate date
);

CREATE TABLE CARS
(
	carID INT PRIMARY KEY,
	model INT,
    year INT,
    brand VARCHAR(50),
    color VARCHAR(10),
    type VARCHAR(10)
);

CREATE TABLE CUSTOMER
(
	customerID INT PRIMARY KEY,
    agencyID INT REFERENCES AGENCY(agencyID),
    insurance VARCHAR(50),
    carID INT REFERENCES CARS(carID),
    reviewID INT REFERENCES REVIEWS(reviewID),
    bookingID INT REFERENCES BOOKING(bookingID)
);

CREATE TABLE REVIEWS
(
	reviewID INT PRIMARY KEY,
    stars INT
);